### ISSUE TITLE
自定义的封面重启失效

### ISSUE THREAD

**Issue by Boycottangent** [totoroyyb/LightDays#1]
点击customize选择了一张图片作为封面，确实生效了，但是重启软件之后，封面就失效了，变成黑屏
UWP旧版本和最新版本都有这个bug，在win10 1709、1803也都有这个问题

**Comment by totoroyyb** [comment]
我暂时没能重现这个问题。请问是自定义任何图片都会出现这个问题吗？还是特定的图片，如果是特定的图片不知能否发来测试一下。谢谢

**Comment by Boycottangent** [comment]
任何图片都会（我估计应该不是一个普遍性的bug，不然应该会有其他用户提到...

**Comment by totoroyyb** [comment]
@Boycottangent 我尝试了多次，无法重现这个问题。我想确认一下打开页面后是显示黑色的吗？能否提供一下图片。按道理，即便软件读取图片失败，显示的应该是白的。你是否使用了暗主题？如果的确使用的是暗主题，我们再继续往下排查。

**Comment by Boycottangent** [comment]
是的，我用了暗主题（如图）
![image](https://user-images.githubusercontent.com/23280916/44043475-8851cdce-9f55-11e8-94a9-f0f77654d96b.png)

**Comment by totoroyyb** [comment]
@Boycottangent 你访问一下 `C:\Users\你的用户名\AppData\Local\Packages\49440TotoroYYB.LightDays_yreay8hxxkfs6\LocalState` 这个地址（将里面的文字替换成你的用户名），打开这个文件夹后，找一下里面是否有名为 `CustomizedCBG.txt` 这个文件（执行这个操作前，确保已经至少自定义过一次以上）。如果有，查看一下文件里面是否有内容，并且文件大小是否与你自定义的图片大小一致。如果没有，请告知！谢谢！

**Comment by Boycottangent** [comment]
文件有内容，与图片大小也是一致的，但是打开是乱码（我用notepad2 替换了系统原生的记事本）试了其他的编辑器也是乱码

**Comment by totoroyyb** [comment]
@Boycottangent 乱码是正常的，不是文本。是照片转换的信息流。问题应该出在加载上，我刚刚重新看了一遍相关代码，应该知道问题在什么地方了。顺便问一下，CPU 的型号？可能是由于软件先把页面渲染出来了，但是这时候还没吧图片读出来，最后导致没能反映到 UI 上。我之前一直在一台双核U系的电脑上测试的，因此可能这里出现了变量。再次感谢反馈，我这个礼拜之内尽可能重写一下那部分的代码，然后发一份测试版的给你。

**Comment by Boycottangent** [comment]
intel Core i5 5200U
非常感谢！

**Comment by totoroyyb** [comment]
@Boycottangent 问题我已经尝试修复，现已提交应用商店，估计两到三个工作日后能收到更新，若还有问题，欢迎反馈！

**Comment by totoroyyb** [comment]
@Boycottangent 不好意思，微软商店审核一直通不过，可能还需要过几天。

**Comment by Boycottangent** [comment]
没事，其实现在主力机已经变成了Mac😥可能没办法立马测试新版本...
您要不考虑一下macOS的版本？Mac下好像稀缺这样好看好用的倒数日app

**Comment by totoroyyb** [comment]
我其实现在也用mac做主力一段时间😂
所以之前审核没通过也没及时处理
我会考虑mac的，但是估计近期希望不大了

On Aug 18, 2018, at 12:44 AM, Boycottangent <notifications@github.com<mailto:notifications@github.com>> wrote:


没事，其实现在主力机已经变成了Mac😥可能没办法立马测试新版本...
您要不考虑一下macOS的版本？Mac下好像稀缺这样好看好用的倒数日app

**Comment by Boycottangent** [comment]
hh好的期待，测试完有问题会再反馈
